//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Compras
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Orden_Compra
    {
        public int IdOrden { get; set; }
        public int No_Orden { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime Fecha_Orden { get; set; }
        public bool Activo { get; set; }
        public int Articulo { get; set; }
        public int Cantidad { get; set; }
        public int Unidad_Medida { get; set; }
        public int Marca { get; set; }
        public decimal Costo_Unitario { get; set; }
    
        public virtual Articulos Articulos { get; set; }
        public virtual Marcas Marcas { get; set; }
        public virtual Medidas Medidas { get; set; }
    }
}
