//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Compras
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedores
    {
        public int IdProv { get; set; }
        public string Nombre { get; set; }
        public string Cedula_o_RNC { get; set; }
        public string Nombre_Comercial { get; set; }
        public bool Activo { get; set; }
    }
}
