//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Compras
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud_Articulos
    {
        public int IdSol { get; set; }
        public int Empleado { get; set; }
        public System.DateTime Fecha_Solicitud { get; set; }
        public int Articulo { get; set; }
        public int Cantidad { get; set; }
        public int Unidad_Medida { get; set; }
        public bool Activo { get; set; }
    
        public virtual Articulos Articulos { get; set; }
        public virtual Empleados Empleados { get; set; }
        public virtual Medidas Medidas { get; set; }
    }
}
